name: llvm toolchain
defaults:
  run:
    shell: bash

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Run custom command before building'
        required: false
        type: string

jobs:
  build_llvm:
    name: Building LLVM and Clang
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
        image: docker://ghcr.io/shinchiro/archlinux:latest
    steps:
      - name: Setup git config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global pull.rebase true
          git config --global rebase.autoStash true
          git config --global fetch.prune true
          git config --global --add safe.directory $PWD

      - uses: actions/checkout@main

      - name: Loading clang root
        id: clang_root_cache
        uses: actions/cache/restore@main
        with:
          path: clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root-${{ github.run_id }}
          restore-keys: ${{ secrets.CACHE_VERSION }}-clang_root

      - name: Loading x86_64 toolchain
        id: x86_64_cache
        uses: actions/cache/restore@main
        with:
          path: build_x86_64
          key: ${{ secrets.CACHE_VERSION }}-clang-x86_64_toolchain-${{ github.run_id }}
          restore-keys: ${{ secrets.CACHE_VERSION }}-clang-x86_64_toolchain

      - name: Loading repository cache
        id: repository_cache
        if: false
        uses: actions/cache/restore@main
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}
          restore-keys: ${{ secrets.CACHE_VERSION }}-repository

      - name: Running custom command
        if: ${{ github.event.inputs.command != '' }}
        continue-on-error: true
        run: ${{ github.event.inputs.command }}

      - name: Building LLVM with ThinLTO and IR Profile Instrumentation
        if: ${{ steps.clang_root_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DGCC_ARCH=x86-64-v3 -DLLVM_ENABLE_PGO=GEN -DLLVM_ENABLE_LTO=Thin -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -G Ninja -B build_x86_64 -S $PWD
          ninja -C build_x86_64 llvm

      - name: Building x86_64 toolchain
        if: ${{ steps.x86_64_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DGCC_ARCH=core2 -DLLVM_ENABLE_PGO=GEN -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -G Ninja -B build_x86_64 -S $PWD
          ninja -C build_x86_64 llvm-clang

      - name: PGO training with shaderc
        if: ${{ steps.clang_root_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DGCC_ARCH=x86-64-v3 -DLLVM_ENABLE_PGO=GEN -DLLVM_ENABLE_LTO=Thin -DCLANG_PACKAGES_LTO=ON -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -G Ninja -B build_x86_64 -S $PWD
          ninja -C build_x86_64 shaderc

      - name: Merging profraw to profdata
        if: ${{ steps.clang_root_cache.outputs.cache-matched-key == '' }}
        run: |
          llvm-profdata merge $PWD/clang_root/profiles/*.profraw -o llvm.profdata
          rm -rf $PWD/clang_root/profiles/* || true

      - name: Building LLVM with ThinLTO and PGO
        if: ${{ steps.clang_root_cache.outputs.cache-matched-key == '' }}
        run: |
          cmake -DTARGET_ARCH=x86_64-w64-mingw32 -DGCC_ARCH=x86-64-v3 -DLLVM_ENABLE_LTO=Thin -DLLVM_ENABLE_PGO=USE -DLLVM_PROFDATA_FILE="llvm.profdata" -DCOMPILER_TOOLCHAIN=clang -DCMAKE_INSTALL_PREFIX=$PWD/clang_root -DMINGW_INSTALL_PREFIX=$PWD/build_x86_64/x86_64-w64-mingw32 -DSINGLE_SOURCE_LOCATION=$PWD/src_packages -G Ninja -B build_x86_64 -S $PWD
          ninja -C build_x86_64 llvm
          
      - name: Cleanup
        run: |
          rm -rf {build_x86_64}/{toolchain,packages} || true
          rm -rf $PWD/clang_root/llvm-thinlto || true

      - name: Collecting logs
        if: always()
        run: |
          mkdir -p build_x86_64_logs
          cp -fr $(find build_x86_64 -type f -iname "*-*.log") build_x86_64_logs || true
          7z a -m0=lzma2 -mx=9 -ms=on logs.7z build*logs

      - name: Uploading logs
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: logs
          path: logs.7z

      - name: Uploading toolchain
        uses: actions/upload-artifact@master
        if: always()
        with:
          name: toolchain
          path: clang_root

      - name: Saving clang root
        uses: actions/cache/save@main
        with:
          path: clang_root
          key: ${{ secrets.CACHE_VERSION }}-clang_root-${{ github.run_id }}

      - name: Saving x86_64 toolchain
        uses: actions/cache/save@main
        with:
          path: build_x86_64
          key: ${{ secrets.CACHE_VERSION }}-clang-x86_64_toolchain-${{ github.run_id }}

      - name: Saving repository cache
        if: false
        uses: actions/cache/save@main
        with:
          path: src_packages
          key: ${{ secrets.CACHE_VERSION }}-repository-${{ github.run_id }}
